language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27

before_install:
 - chmod +x ./gradlew
script:
  - ./gradlew clean build

#TODO: deploy artifacts
#deploy:
#  provider: script
#  script: ./gradlew bintrayUpload
#  on:
#    branch: master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache